version: '2'
services:
  x-web: &web-base
    build: .
    environment:
      - APP_NAME=app
      - APPLICATION=japp
      - UWSGI_APP_LOGGING_ENABLED=true
      - FLASK_ENV=development
    volumes:
      - .:/usr/src/app

  redis:
    restart: unless-stopped
    image: redis:5-alpine
    volumes:
      - ./data/redis:/data

  web:
    <<: *web-base
    restart: unless-stopped
    build: .
    environment:
      - APP_NAME=app
      - APPLICATION=app
      - UWSGI_APP_LOGGING_ENABLED=true
      - FLASK_ENV=development
    volumes:
      - .:/usr/src/app
    links:
      - redis
      - celery
    ports:
      - '8000:8000'
    command: uwsgi --ini /usr/src/app/uwsgi.ini
  
  celery:
    <<: *web-base
    volumes:
      - .:/usr/src/app
    links:
      - redis
    command: ["celery", "worker", "-l", "debug", "-A", "app.tasks", "--uid", "webapp"]